version: '3.9'

services:
  backend:
    build:
      context: ./real_estate_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./real_estate_api:/app
      - ./data:/app/data
      - ./ml/model_store:/app/model_store
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./real_estate_frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./real_estate_frontend:/app
    environment:
      - NODE_ENV=development