version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_img:v1
    ports:
      - "8000:8000"
    volumes:
      - "../data:/app/data"
      - "../ml/model_store:/app/model_store"
    command: uvicorn app.main:app --host=0.0.0.0 --port=8000